# Generated by Django 3.1.7 on 2021-10-14 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_teliphone', models.CharField(max_length=8)),
                ('nombre_des_chambres', models.IntegerField()),
                ('nombre_des_etoiles', models.IntegerField()),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
