# Generated by Django 3.1.7 on 2021-10-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20211014_2211'),
        ('reservations', '0003_auto_20211018_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel'),
        ),
    ]
